name: "tests"
on:
  pull_request:
  push:
    branches:
      - master
      - main
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: go test ./...

      - name: Calc coverage
        run: |
          go test -coverpkg=./... ./... -count=1 -coverprofile=cover.cov.tmp -v
#          cat cover.cov.tmp | grep -v "main.go" > profile.cov
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GO111MODULE=off go get github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
